config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resource :dashboard, only: :show

  resource :registration, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resource :password_reset, only: [:new, :create, :edit, :update]

  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  MINIMUM_PASSWORD_LENGTH = 8

  has_secure_password

  validates :password, length: {minimum: MINIMUM_PASSWORD_LENGTH}

  validates :email, presence: true

  validates :email, uniqueness: true

  normalizes :email, with: ->(email) { email.strip.downcase }

  has_many :sessions, dependent: :destroy

  generates_token_for :reset_password, expires_in: 1.hour do
    password_salt.last(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  def require_authentication
    restore_authentication || request_authentication
  end

  def restore_authentication
    session = session_from_cookies

    if session.present?
      Current.user = session.user
    end
  end

  def request_authentication
    redirect_to new_session_path, notice: "You must be signed in to perform that action"
  end

  # @param user [User]
  def sign_in(user)
    session = user.sessions.create!

    cookies.signed.permanent[:session_id] = {value: session.id, httponly: true}
  end

  def sign_out
    session_from_cookies.destroy!

    cookies.delete(:session_id)
  end

  def session_from_cookies
    Session.find_by(id: cookies.signed[:session_id])
  end

  def redirect_if_signed_in
    if restore_authentication
      redirect_to root_path, notice: "You are already signed in"
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_authentication

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :redirect_if_signed_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present?
      token = user.generate_token_for(:password_reset)

      UserMailer.with(user: user, password_reset_token: token).password_reset.deliver_later

      redirect_to root_path, notice: "Email sent with password reset instructions"
    else
      flash.now[:notice] = "No user found with that email address"

      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    user = User.find_by_password_reset_token(params[:password_reset_token])

    if user.blank?
      flash[:notice] = "Invalid token. Try again by requesting a new password reset link."

      redirect_to new_password_reset_path
    elsif user.update(password_reset_params)
      sign_in(user)

      redirect_to dashboard_path, notice: "Password has been successfully reset"
    else
      flash.now[:notice] = user.errors.full_messages.to_sentence

      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_reset_params
    params.require(:password_reset).permit(:password, :password_confirmation)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :redirect_if_signed_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)

      redirect_to dashboard_path, notice: "You have successfully registered!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_authentication, only: :destroy
  before_action :redirect_if_signed_in, only: [:new, :create]

  def new
  end

  def create
    user = User.authenticate_by(session_params)

    if user.present?
      sign_in(user)

      redirect_to dashboard_path, notice: "Logged in with #{user.email}"
    else
      flash.now[:notice] = "Invalid email or password"

      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    sign_out

    redirect_to root_path, notice: "You have been signed out"
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.html.erb
<h1>Private dashboard</h1>

<p>Welcome <%= Current.user.email %>,</p>

<p>This page should only be accessible to authenticated users.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Authentication Course" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- <meta name="apple-mobile-web-app-capable" content="yes"> -->
    <!-- <meta name="mobile-web-app-capable" content="yes"> -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <!-- <link rel="icon" href="/icon.png" type="image/png"> -->
    <!-- <link rel="icon" href="/icon.svg" type="image/svg+xml"> -->
    <!-- <link rel="apple-touch-icon" href="/icon.png"> -->

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Sign in", new_session_path %></li>
          <li><%= link_to "Sign up", new_registration_path %></li>
          <li><%= button_to "Sign out", session_path, method: :delete %></li>
        </ul>
      </nav>
    </header>

    <main>
      <%= notice %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Landing page</h1>

<p>This page is public and can be accessed by both authenticated and unauthenticated users.</p>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with scope: :password_reset, url: password_reset_path, method: :patch do |f| %>
  <%= hidden_field_tag :password_reset_token, params[:password_reset_token] %>

  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <%= f.submit "Reset password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Password reset</h1>

<%= form_with url: password_reset_path do |f| %>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <%= f.submit "Reset password" %>
<% end %>